import {
  Image,
  TextIcon,
  UndoIcon,
  RedoIcon,
  Download,
  Undo2,
  Redo2,
  Loader2,
  Trash2,
  Type,
  ImageIcon,
  ListIcon,
  ArrowUpToLine,
  ArrowDownToLine,
  AlignLeft,
  AlignCenter,
  AlignRight,
} from "lucide-react";

export const ICONS = {
  text: TextIcon,
  image: Image,
  redo: RedoIcon,
  undo: UndoIcon,
  download: Download,
  undo2: Undo2,
  redo2: Redo2,
  loader2: Loader2,
  trash2: Trash2,
  type: Type,
  imageIcon: ImageIcon,
  listIcon: ListIcon,
  arrowUpToLine: ArrowUpToLine,
  arrowDownToLine: ArrowDownToLine,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
};
